### ISSUE TITLE
Have you tested the llava-interleave-qwen-7b model on the ego4d_video_train.json dataset?

### ISSUE THREAD

**Issue by Xavier-Zeng** [zjysteven/lmms-finetune#12]
I test, but get some errors like this:
![image](https://github.com/user-attachments/assets/332dacf5-af6c-473a-b202-b9354fff20a4)

**Comment by zjysteven** [comment]
On my end it runs with no problem. Take a look at #8. If you are using local checkpoint, make sure you have chat_template.json (or the tokenizer_config.json has "chat_template" attribute). Also try upgrading the version of your transformers library.

**Comment by Xavier-Zeng** [comment]
> On my end it runs with no problem. Take a look at #8. If you are using local checkpoint, make sure you have chat_template.json in your checkpoint folder (or the tokenizer_config.json has "chat_template" attribute). Also try upgrading the version of your transformers library.

thanks，I try this, it also seems work.
```python
chat_template = "{% for message in messages %}{{'<|im_start|>' + message['role'] + '\n'}}{# Render all images first #}{% for content in message['content'] | selectattr('type', 'equalto', 'image') %}{{ '<image>' }}{% endfor %}{# Render all text next #}{% for content in message['content'] | selectattr('type', 'equalto', 'text') %}{{ '\n' + content['text'] }}{% endfor %}{{'<|im_end|>' + '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant\n' }}{% endif %}"
            
cur_text = self.processor.apply_chat_template(cur_text, tokenize=False, add_generation_prompt=False, chat_template=chat_template)
```

**Comment by zjysteven** [comment]
Yes this way it can work too. Closing now. Feel free to reopen if there are any other questions.
