### ISSUE TITLE
Pre-compute vision encoder features

### ISSUE THREAD

**Issue by nisargshah1999** [zjysteven/lmms-finetune#18]
Hi,

Thanks for very useful and interesting work
I was wondering, if there is any easy way to precompute vision encoder features for training(and load them), so memory complexity issue can be solved

**Comment by zjysteven** [comment]
That's a good idea and definitely possible. I can try to support such options in the following days. Meanwhile if you'd like to implement something yourself I might be able to give some high level ideas. Let me know.

**Comment by nisargshah1999** [comment]
Good to hear, sure, I can work on that
Let me know the pointers(and anything to not miss), as I have less experience working with hf modules

**Comment by zjysteven** [comment]
After thinking about it the best option would be that I (and our maintainers) to implement it because there will be some model loading/unloading logics involved which are coupled with the existing logics. I'm already working on it and it should be available soon.
