### ISSUE TITLE
想要支持text-only数据需要做哪些修改呢

### ISSUE THREAD

**Issue by fedshyvana** [zjysteven/lmms-finetune#2]
感谢作者开源对大视觉语言模型训练的相关工具！想问一下现阶段想要支持text-only数据应该做哪些修改呢？据我所知llava是有用text-only数据训练的，并且作者声明对维持模型的表现至关重要。llava 1.5据我理解好像是通过这里绕开你所提到的deepspeed对于需要用所有parameters的需求：https://github.com/haotian-liu/LLaVA/blob/c121f0432da27facab705978f83c4ada465e46fd/llava/model/llava_arch.py#L237。

**Comment by zjysteven** [comment]
没错，llava-1.5你引用的这行能够巧妙避开那个问题（parameter参与了forward但相应输出不算loss）。我之前试图用过同样的方法，但怎么和huggingface模型的参数作兼容稍微有点麻烦（比如传shape为[0, x, x, x]的pixel_values会报错）。这个我会尽快再尝试一下。

**Comment by zjysteven** [comment]
看了一下要用llava原本方法的话肯定得改transformers内部代码了，不觉得huggingface有理由支持。目前想到的办法是写一个sampler保证每个batch里至少有一个instance有图像/视频，这样除了batch_size=1和训练集中text-only data数量显著超过multimodal data的corner case之外应该都能work了。如果有其他想法/建议欢迎讨论👏

**Comment by fedshyvana** [comment]
嗯唯一其他能想到的就是自己改一个custom forward，然后monkey patch一下，但这样子如果hf官方不支持的，要长期兼容也比较麻烦

**Comment by zjysteven** [comment]
对恐怕维护成本太高，而且报错主要是clip内部attention对batch_size为0输入的shape做推断时（比如view）有问题。这个之后拼接image embedding和text embedding目前也不知道有没有问题。还是写了sampler，测了一个简单case（`example_data/single_image_has_text_only.json`，4个数据其中2个是text-only，per_device_batch_size=2），跑了50个epoch没有问题。
