### ISSUE TITLE
error occurred: The input provided to the model are wrong. The number of image tokens is 4 while the number of image given to the model is 2. This prevents correct indexing and breaks batch generation.

### ISSUE THREAD

**Issue by ReadyTeresa** [zjysteven/lmms-finetune#21]
My text prompt is:
According to the text and image identify the same attribute of the two product. [{'text':xxx,'image':<>},{'text':xxx,'image':<>]
Then, the error occurred: The input provided to the model are wrong. The number of image tokens is 4 while the number of image given to the model is 2. This prevents correct indexing and breaks batch generation.

**Comment by zjysteven** [comment]
Were you able to identify the specific dataset entry in your data json file that caused the error? If so could you paste it here? The current description does not provide enough information for me to exactly know what's going on.
