### ISSUE TITLE
LLaVA-OneVision for single-image, multi-image, and video

### ISSUE THREAD

**Issue by KevinH48264** [zjysteven/lmms-finetune#25]
Thank you for the great work here!

LLaVA-OneVision seems to be the latest model from the LLaVA family of models that performs well out of open source LMMs. While it's still early, raising it here as others in the community may start to look at it.

https://llava-vl.github.io/blog/2024-08-05-llava-onevision/

**Comment by zjysteven** [comment]
Thanks for raising this. We've also noticed it and including it into lmms-finetune is part of our recent plan.

**Comment by zjysteven** [comment]
We will wait a bit until the model implementation is merged into the main branch of transformers.
https://huggingface.co/llava-hf/llava-onevision-qwen2-0.5b-ov-hf/discussions/1
https://github.com/huggingface/transformers/pull/32673

**Comment by btekin** [comment]
Are there any updates on this? It seems LLaVA-Onevision got merged into the main branch of transformers now: https://github.com/huggingface/transformers/pull/32673

**Comment by zjysteven** [comment]
We will include it once we are free, probably in 2 - 3 weeks.
