### ISSUE TITLE
How to support initializing training from a checkpoint?

### ISSUE THREAD

**Issue by KevinH48264** [zjysteven/lmms-finetune#29]
Thanks for the great work again! 

I saw that we can use the checkpoints for inference, but I was struggling a bit to understand how to support initializing training from a checkpoint?

Is this functionality supported or perhaps not yet?

Thanks!

**Comment by zjysteven** [comment]
By "initializing training from a checkpoint" do you mean you want to do multiple fine-tuning runs?

**Comment by KevinH48264** [comment]
Yep, so suppose I train a model using one set of data, then I have one
finetuned model.

Now let’s say I have another set of data that I want to continue training
the finetuned model on.

I was wondering if there’s a way to do that? Usually I can initialize the
model not from the pretrained huggingface weights, but rather the model
checkpoint. But I was running into some difficulties with that method.

**Comment by zjysteven** [comment]
Yes that is possible. After finetuning, just load your finetuned model using following the same process as if you were using the checkpoint for inference, and that should be it; after loading you can do the finetuning.

You mentioned there were some difficulties. What were those exactly?

**Comment by KevinH48264** [comment]
Oh okay, so the finetuning script works well when MODEL_ID= model id from supported_models.py. 

The problem is that I currently just naively swap out MODEL_ID to the full path of my checkpoint (tried both the latest / root checkpoint path, and checkpoint-#### subdirectory).

The error that I get is in train.py, where I get:

obj = dtype(**inputs)
...lmms-finetune/arguments.py", line 14, in __post_init__
File "<string>", line 4, in __init__
File "<string>", line 4, in __init__
  assert self.model_id in MODEL_HF_PATH, f"Unknown model_id: {self.model_id}"
    AssertionError: Unknown model_id: "<model checkpoint path>"


I think I can plausibly see a way to load the model from the model id in inference.py and then integrate that into train.py somehow, but was just wondering if there was an easier way of supporting this?

**Comment by zjysteven** [comment]
We pushed a commit supporting this (https://github.com/zjysteven/lmms-finetune/commit/7d417ecd061e9cf4361402b8ae6a568a043693b8). You can pass `--model_local_path PATH/TO/CKPT` to the training script to enable this (note you still have to provide the corresponding `model_id`). For the particular error message you posted above it seemed somehow `model_id` is an empty string.

**Comment by KevinH48264** [comment]
Got it, thank you! I'll try it out.

And I just removed the model_id, it was previously the path to the checkpoint.
