### ISSUE TITLE
Any plans to support Qwen2-VL?

### ISSUE THREAD

**Issue by KevinH48264** [zjysteven/lmms-finetune#36]
I believe the format should be similar to Qwen-VL, but wondering if there are plans to support Qwen2-VL as the latest open source LMM?

**Comment by zjysteven** [comment]
Yes it is in our plan!

**Comment by KevinH48264** [comment]
Oh that's awesome, is there an ETA on it?

**Comment by zjysteven** [comment]
@linyueqian will be implementing it as I'm on the job market. He will have a better idea on the ETA.

**Comment by linyueqian** [comment]
Since the chat template of the Qwen2-VL in Huggingface does not support the assistant mask yet, we have opened a PR to see if the hf staff can help merge the change. The eta may vary.

**Comment by KevinH48264** [comment]
Ah I see, I'm assuming it supports mainly just masking the final assistant message?

**Comment by zjysteven** [comment]
@KevinH48264 That's right. Being able to mask the final assistant message is the easiest way to accurately construct training labels.

**Comment by KevinH48264** [comment]
Does this mean that if I only cared about masking the final assistant message, I could integrate Qwen2-VL in HuggingFace to this repo right now?

**Comment by zjysteven** [comment]
I may not fully understand the question, but there is always another option of manually masking the assistant message (or equivalently, manually constructing labels; which might be a bit cumbersome though). So yes you could definitely integrate Qwen2-VL. What we are trying to do is to use built-in function of huggingface's chat template for achieving that.

**Comment by linyueqian** [comment]
@KevinH48264 I just updated our codebase to include Qwen2-VL. Feel free to try and see if it works.
