### ISSUE TITLE
vision_feature_layer should be -2 not -1 in llava interleave

### ISSUE THREAD

**Issue by sohananisetty** [zjysteven/lmms-finetune#4]
In the llava-next interleave codebase, they have used the penultimate hidden features of Siglip vision encoder but the hugging face version has vision_feature_layer= -1. LLava 1.5 has vision_feature_layer = -2 too. Is the huggingface interleave model different from the original?

**Comment by zjysteven** [comment]
From the config it indeed seems there is a discrepancy. Would you mind opening an issue in huggingface transformers to see if there's a reason for them choosing -1?

**Comment by zucchini-nlp** [comment]
Hey! I am the one who added llava-interleave and indeed seems like the config for original interleave model isn't consistent with the SigLip impl in their codebase. Thanks for noting it, I'll change the selection layer to "-1" in out configs

**Comment by zjysteven** [comment]
Thanks for looking into this @zucchini-nlp! Much appreciated.

**Comment by zucchini-nlp** [comment]
My bad on reading the issue fast, I didn't notice that you meant "selection layer should be -2". The selection layer is -1 in HF impl, which is correct, because the original impl doesn't use half of the params from config. They have most of the code hardcoded. Sorry for confusion

**Comment by sohananisetty** [comment]
In the original code they use the 2nd last layer of siglip. They first delete the last layer in load model and access - 1 layer In forward function. Since the huggingface implementation does not modify the vision encoder shouldnt it be the 2nd last encoder layer.

**Comment by zucchini-nlp** [comment]
Yes, we also deleted the last layer of Siglip when creating the model, otherwise we wouldn't be able to load weights. You can check the config that Siglip has one less hidden layers in Llava than in the original Siglip repo. So using the -1 here is basically same as -2

**Comment by sohananisetty** [comment]
Got it. Thanks for the clarification!
