### ISSUE TITLE
The number of image tokens is 2 while the number of image given to the model is 1. 

### ISSUE THREAD

**Issue by 98986oiuoy** [zjysteven/lmms-finetune#48]
Fine-tune llava-interleave-qwen-0.5b, do I have to use the multi_images.json format? Can't use celeba_image_train.json data format?
![a8aab90b5fd2b325a9766af4bb11036](https://github.com/user-attachments/assets/62e2f065-f39b-4685-9a96-d8fdd9835734)

**Comment by zjysteven** [comment]
Previously there was a bug, and it has been fixed by https://github.com/zjysteven/lmms-finetune/commit/5db747c86bc899e2664af3f88343a0cbf31c0ae1. Could you pull the latest code and try again?

**Comment by 98986oiuoy** [comment]
> Previously there was a bug, and it has been fixed by [5db747c](https://github.com/zjysteven/lmms-finetune/commit/5db747c86bc899e2664af3f88343a0cbf31c0ae1). Could you pull the latest code and try again?

I finally got what I need to report for the group meeting tomorrow, thank you a lot!!!!!!!!! LOVE YOU!!!!!!!
