### ISSUE TITLE
'height' and 'width' referenced before assignment 

### ISSUE THREAD

**Issue by TonyJiang17** [zjysteven/lmms-finetune#54]
num_image_tokens = self.processor._get_number_of_features(orig_height, orig_width, height, width)

I got this error and it pointed to this line of code in the 'llava_next_video' collator.py, it seems that those two parameters were not assigned before referencing?

**Comment by zjysteven** [comment]
Yes there is a bug. I don't have the access to my development environment and can only push a fix some time after Thanksgiving.

**Comment by zjysteven** [comment]
Just pushed a fix. Let me know if it works.
