### ISSUE TITLE
Regarding the issue of training templates in Qwen2VLDataCollator 

### ISSUE THREAD

**Issue by Asunatan** [zjysteven/lmms-finetune#57]
Hello, I am a beginner in the field of VLM and have a question regarding the training template issue. In the Qwen2VLDataCollator you provided, I noticed there are some additional fields.
![image](https://github.com/user-attachments/assets/10e1d1c1-1ba1-4273-a63d-19446b2a87d9)
This differs from directly applying
`apply_chat_template_text= self.processor.apply_chat_template(cur_text, tokenize=False, add_generation_prompt=True,)`which seems to result in some differences. Could this lead to discrepancies during prediction?
Below is the result obtained directly from applying apply_chat_template:
![image](https://github.com/user-attachments/assets/a19b3749-54e5-443f-bdfc-56a44631b2ec)
The gpt_response obtained from apply_chat_template appears to lack the fields such as [ {"type":"text", "text":. I found that the source of the issue seems to be:
![image](https://github.com/user-attachments/assets/6eeda8f9-bffb-401f-a9c4-a3f4a4105087)
I am curious whether the differences between these two could lead to training biases.

**Comment by Elenore1997** [comment]
I found the same problem as you mention. So I directly edit the code:
cur_text.append({
      "role": "assistant",
      # "content": [
      #     {"type": "text", "text": text},
      # ]
      "content": text
  })

**Comment by Asunatan** [comment]
Yes, I have adopted the same strategy as you, but is it correct to do so?

**Comment by Asunatan** [comment]
> I have adopted the same strategy as you, but is it correct to do so?

Yes, I have adopted the same strategy as you, but is it correct to do so?

**Comment by Asunatan** [comment]
> I found the same problem as you mention. So I directly edit the code: cur_text.append({ "role": "assistant", # "content": [ # {"type": "text", "text": text}, # ] "content": text })

Yes, I have adopted the same strategy as you, but is it correct to do so?

**Comment by Elenore1997** [comment]
I think it is ok to edit like this, I have trained model using this repository (edit this few lines of code) and inference with qwen2vl official code (using apply_chat_template) and get the correct result.

**Comment by Asunatan** [comment]
> I think it is ok to edit like this, I have trained model using this repository (edit this few lines of code) and inference with qwen2vl official code (using apply_chat_template) and get the correct result.

Thank you, this is very helpful to me.

**Comment by zjysteven** [comment]
@Asunatan @Elenore1997 Yes I think the proposed fix looks good. Sorry for not being able to respond earlier; I was moving the past few days. Tagging @linyueqian to be aware of this.

**Comment by linyueqian** [comment]
Yes, as mentioned in #56, we should directly use the text as the content value. Just updated in the latest commit.
