### ISSUE TITLE
example_image.sh script fails with image token mismatch error in LLaVa

### ISSUE THREAD

**Issue by gn64** [zjysteven/lmms-finetune#63]
Describe the bug
I am trying to run the example_image.sh script from the example_scripts folder using LLaVa (version 1.5-7B) for fine-tuning. However, the process fails with an error regarding mismatched image tokens, specifically:

```
ValueError: The input provided to the model are wrong. 
The number of image tokens is 1014 while the number of image given to the model is 2.
```

Despite following the steps outlined in the example, the script does not appear to handle the image token configuration correctly.
Steps to reproduce

Clone the repository and set up the Python environment as instructed.
Run $ bash example_scripts/example_image.sh
Observe the ValueError during training.
Expected behavior
The script should successfully launch the training process for image-based fine-tuning with the specified model, without any mismatched token errors.

Actual behavior
The training process immediately fails because the model expects a specific number of image tokens, but only receives a different batch size or token count. The error message indicates a mismatch between “image tokens” and “the number of images given to the model.”

**Comment by zjysteven** [comment]
Thank you for reporting this, and I could reproduce on my end. The fix would simply be to change the `MODEL_MAX_LEN` from 512 to a large number say 1024. The cause of this "bug" is due to the change in the way that transformers library handles the expansion of image tokens (as discussed in #43).

**Comment by gn64** [comment]
Thank you very much. It works!
