### ISSUE TITLE
working inference code for video model?

### ISSUE THREAD

**Issue by Namzakku** [zjysteven/lmms-finetune#7]
Hi!
I tried to combine the inference instruction you provided and follow the inference code from the hf tutorials in
https://colab.research.google.com/drive/1dTdro-k7NFqRgGq5-TlGHM-6k2sYQhXp#scrollTo=4ccbd183-f15a-4f94-a526-9ceeec3f61e0
but got meaningless results. 

I also tried to use your collator but got `CUDA error: device-side assert triggered` in the generate().

Can you provide a working code or give some hints?

**Comment by zjysteven** [comment]
I will take a look asap. By "meaningless results" do you mean the generated text completely go off or it's not desirable enough?

**Comment by Namzakku** [comment]
The generated text I got was a mixture of symbols or a mixture of texts from multiple languages and it didn't answer any of the question at all.

Any one more thing I got concern is that the train loss I got during training declined significantly only after a few steps. You can see in the below graph.
![image](https://github.com/user-attachments/assets/e4a7ae0a-8892-4179-a31d-805123619270)
I tried many times but still got the same situation. I used the same dataset that worked with the llava video hf tutorial but the loss was more reasonable.

**Comment by zjysteven** [comment]
I see. I'm running experiments now. For the loss, there indeed is a difference between the implementation here and that tutorial colab you shared: While their labels include both questions and answers (the model will also learn to predict user's questions), ours only set labels to account for the answers (the model only learns to predict the responses). Not sure if this fully explains the loss differences though.

**Comment by zjysteven** [comment]
Hi @Namzakku, I've put up a full example notebook here https://colab.research.google.com/drive/1ejXG58cpMXvkcsx2qqTFK2BqWBVBEr7Y?usp=sharing that showcases a training run and the following inference of llava-next-video-7b, with the data from ShareGPT4Video. The output of the finetuned model makes sense to me and indicates that the training worked (there is noticeable difference between the output of the original and the finetuned model). The exact running script is updated in the `example.sh` in the repo. ***Please pull the latest code and try again.***

For the loss scale, notice that in the previous colab tutorial you shared it was using a gradient accumulation steps of 8, while in my `example.sh` it is 1. This actually could well explain the discrepancy in loss scale where initially you would see a loss of 10+ (but if you also use gradient_accumulation_steps=8 you would observe a loss of ~1 or ~2).

**Comment by Namzakku** [comment]
Thanks for the great notebook! 
I have tested a bunch of work today and it works like a charm!
Regarding the loss scale, indeed there is a difference of gradient accumulation as you mentioned.

Also, I found a tiny problem when training. 
For some minor videos in my dataset, they only have 5-6 frames and is less than the default 8 frames, which made the training crash. After I reduced the default frame to 4, it worked correctly.
I didn't experience this when using the hf notebook, maybe they have additional padding somewhere?
I haven't tried rasing the default frame to 16 or 32 yet, so further testing should be needed.

**Comment by zjysteven** [comment]
Glad to know it worked. For the number of frames, I could guess where the error came from, but do you still have the error message available by any chance so that I can confirm?

**Comment by Namzakku** [comment]
sure! this is the error I got.

```
Traceback (most recent call last):
  File "/workspace/lmms-finetune/train.py", line 156, in <module>
    train()
  File "/workspace/lmms-finetune/train.py", line 142, in train
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2236, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/usr/local/lib/python3.10/dist-packages/accelerate/data_loader.py", line 464, in __iter__
    next_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/workspace/lmms-finetune/collators/llava_next_video.py", line 37, in __call__
    videos[i] = np.concatenate([video, pad], axis=0)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 398 and the array at index 1 has size 7
```

**Comment by zjysteven** [comment]
Thanks. I can reproduce, and it turned out that there is some dimension issue with the padding. Will push a fix soon.
